### ISSUE TITLE
iidy fails silently if AWS metadata service 404s

### ISSUE THREAD

**Issue by cschmidt** [unbounce/iidy#111]
If you happen to be running iidy in an environment where the credentials are not found, iidy will fail silently. In particular, I noticed this running iidy under AWS Cloud9. Running `iidy render` on a template would produce no output.

Manually configuring AWS credentials with `aws configure` works around the issue.

**Comment by cschmidt** [comment]
@tavisrudd noted that the tell-tale sign you were running into this issue was that you'd get a 404 from the AWS metadata service (http://169.254.169.254/latest/meta-data/iam/)

**Comment by cschmidt** [comment]
Just some further thinking on this. I'm not sure if the lack of iam meta-data is actually a bug in the Cloud9 environment. Reading through the docs on [AWS Managed Temporary Credentials](https://docs.aws.amazon.com/cloud9/latest/user-guide/auth-and-access-control.html#auth-and-access-control-temporary-managed-credentials) it seems like this might be a feature.

**Comment by tavisrudd** [comment]
If not a bug in Cloud9, it's a bug in the aws-sdk for js. That's what handles the lookup via the metadata service. Regardless, we can improve `iidy`'s error reporting for this case.

**Comment by tavisrudd** [comment]
```
cschmidt:~/environment (master) $ iidy --debug render cfn-template.yaml 
error:  Error: null
    at IncomingMessage.<anonymous> (/snapshot/cf_templates/node_modules/aws-sdk/lib/util.js:864:34)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
```
is the stack trace Carl encountered.

**Comment by tavisrudd** [comment]
A related issue is that if you run `iidy` from a location that has neither `~/.aws/` or the AWS metadata service it will hang for a while before exiting with `error: connect ETIMEDOUT 169.254.169.254:80`.

**Comment by tavisrudd** [comment]
PR #120 addresses `ETIMEDOUT` and `ECONNREFUSED` but not the original 404 that @cschmidt encountered.
