### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by a5a5a9** [unbounce/iidy#247]
iidy help
/home/kile/iidy/lib/main.js:414
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kile/iidy/bin/iidy:4:1)
    at Module._compile (module.js:577:32)

**Comment by tavisrudd** [comment]
Hi @a5a5a9 can you give us some more details about which version of iidy you're encountering this on and how you installed it?

**Comment by a5a5a9** [comment]
Hi, it works now, I had to install newest version of node 12.X.
